---
name: "jellyfin-plugin-smart-collections"
guid: "bc4aad2e-d3d0-4725-a5e2-fd07949e5b42"
version: "5" # Please increment with each pull request
jellyfin_version: "10.5.0" # The earliest binary-compatible version
owner: "jellyfin"
nicename: "Smart Collections"
description: "Automatically create Smart Collections based on Tags"
overview: "Automatically create Smart Collections based on Tags"
category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.SmartCollections.dll"
build_type: "dotnet"
dotnet_configuration: "Release"
dotnet_framework: "netstandard2.1"
